import { useEffect, useRef, useState, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import * as echarts from 'echarts';
import './styles.css';

type Signal={key:string;display_name:string;description:string};
type Daily={date:string;rank_ic:number;count:number;quantile_returns:number[];long_short_return:number};
type Report={forward_days:number;mean_rank_ic:number;rank_ic_ir:number;rank_ic_positive_rate:number;rank_ic_stddev:number;mean_long_short_return:number;observation_count:number;evaluated_dates:number;daily:Daily[]};
type Payload={report:{definition:Signal;observation_count:number;first_date:string;last_date:string;reports:Report[]}};
type StrategySummary={experiment_id:string;name:string;created_at:string;total_return:number;annualized_return:number;max_drawdown:number;sharpe_ratio:number;calmar_ratio:number;mean_rank_ic:number;lookback_days:number;top_n:number;rebalance_every:number};
type Equity={date:string;equity:number;drawdown:number};
type Experiment={experiment_id:string;name:string;config:{strategy:{lookback_days:number;top_n:number;rebalance_every:number}};backtest:{metrics:{total_return:number;annualized_return:number;sharpe_ratio:number;calmar_ratio:number;max_drawdown:number};equity_curve:Equity[];benchmark_curve:{date:string;close:number}[]}};
const pct=(n:number)=>`${(n*100).toFixed(2)}%`;
function Chart({option}:{option:echarts.EChartsOption}) { const ref=useRef<HTMLDivElement>(null); useEffect(()=>{const c=echarts.init(ref.current!); c.setOption(option); const resize=()=>c.resize(); addEventListener('resize',resize); return()=>{removeEventListener('resize',resize);c.dispose()};},[option]); return <div className="chart" ref={ref}/> }
function Detail(){const [signals,setSignals]=useState<Signal[]>([]),[key,setKey]=useState(decodeURIComponent(location.pathname.split('/').pop()||'momentum_60')),[data,setData]=useState<Payload|null>(null),[error,setError]=useState('');
useEffect(()=>{fetch('/api/v1/signals').then(r=>r.json()).then(setSignals)},[]);
useEffect(()=>{setData(null);setError('');fetch(`/api/research/signals/${key}/report`).then(async r=>r.ok?r.json():Promise.reject((await r.json()).error)).then(setData).catch(setError)},[key]);
const report=data?.report.reports[0]; const daily=report?.daily??[]; const dates=daily.map(x=>x.date); const rolling=daily.map((_,i)=>daily.slice(Math.max(0,i-59),i+1).reduce((s,x)=>s+x.rank_ic,0)/Math.min(i+1,60));
const nav=(which:(d:Daily)=>number)=>{let x=1;return daily.map(d=>x*=1+which(d))};
return <><header><b>Prajna Quant</b><nav><a href="/">策略绩效</a><a className="active" href="/factors">因子研究</a></nav><select value={key} onChange={e=>setKey(e.target.value)}>{signals.map(s=><option key={s.key} value={s.key}>{s.display_name}</option>)}</select></header><main><h1>{data?.report.definition.display_name??'ETF 信号研究'}</h1><p>{data?.report.definition.description??'正在加载已保存的研究报告'}</p>{error?<div className="notice">{error}。请执行 <code>signal-research --signal {key}</code> 后刷新。</div>:!report?<div className="notice">加载报告中…</div>:<><section className="metrics">{[['观察数',report.observation_count.toLocaleString()],['Mean Rank IC',report.mean_rank_ic.toFixed(4)],['ICIR',report.rank_ic_ir.toFixed(3)],['IC 胜率',pct(report.rank_ic_positive_rate)],['多空平均收益',pct(report.mean_long_short_return)],['有效截面',String(report.evaluated_dates)]].map(([k,v])=><div className="metric" key={k}><small>{k}</small><strong>{v}</strong></div>)}</section><section className="grid"><Panel title="Rank IC 时间序列"><Chart option={{tooltip:{trigger:'axis'},xAxis:{type:'category',data:dates},yAxis:{type:'value'},dataZoom:[{type:'inside'},{type:'slider'}],series:[{type:'line',showSymbol:false,data:daily.map(x=>x.rank_ic)}]}}/></Panel><Panel title="Rolling Rank IC（60期）"><Chart option={{tooltip:{trigger:'axis'},xAxis:{type:'category',data:dates},yAxis:{type:'value'},dataZoom:[{type:'inside'},{type:'slider'}],series:[{type:'line',showSymbol:false,data:rolling,color:'#0f766e'}]}}/></Panel><Panel title="分组累计净值"><Chart option={{tooltip:{trigger:'axis'},legend:{},xAxis:{type:'category',data:dates},yAxis:{type:'value'},dataZoom:[{type:'inside'},{type:'slider'}],series:Array.from({length:daily[0]?.quantile_returns.length??0},(_,i)=>({name:`Q${i+1}`,type:'line',showSymbol:false,data:nav(d=>d.quantile_returns[i])}))}}/></Panel><Panel title="多空累计净值"><Chart option={{tooltip:{trigger:'axis'},xAxis:{type:'category',data:dates},yAxis:{type:'value'},dataZoom:[{type:'inside'},{type:'slider'}],series:[{name:'Q5-Q1',type:'line',showSymbol:false,data:nav(d=>d.long_short_return),color:'#dc2626'}]}}/></Panel><Panel title="IC Decay"><Chart option={{tooltip:{trigger:'axis'},xAxis:{type:'category',data:data.report.reports.map(r=>`${r.forward_days}D`)},yAxis:{type:'value'},series:[{type:'bar',data:data.report.reports.map(r=>r.mean_rank_ic)}]}}/></Panel><Panel title="有效 ETF 数"><Chart option={{tooltip:{trigger:'axis'},xAxis:{type:'category',data:dates},yAxis:{type:'value'},dataZoom:[{type:'inside'},{type:'slider'}],series:[{type:'line',showSymbol:false,data:daily.map(x=>x.count),color:'#7c3aed'}]}}/></Panel></section></>}</main></>}
function Panel({title,children}:{title:string;children:ReactNode}){return <section className="panel"><h2>{title}</h2>{children}</section>}
function Header(){return <header><b>Prajna Quant</b><nav><a href="/">策略绩效</a><a href="/factors">因子研究</a></nav></header>}
function useSort<T>(rows:T[], initial:keyof T){const [sort,setSort]=useState<{key:keyof T;desc:boolean}>({key:initial,desc:true});const sorted=[...rows].sort((a,b)=>{const x=a[sort.key],y=b[sort.key];return (typeof x==='number'&&typeof y==='number'?x-y:String(x??'').localeCompare(String(y??'')))*(sort.desc?-1:1)});const by=(key:keyof T)=>setSort(s=>({key,desc:s.key===key?!s.desc:true}));return {sorted,by,sort}}
function FactorDirectory(){const [signals,setSignals]=useState<Signal[]>([]);const [reports,setReports]=useState<Record<string,Report>>({});useEffect(()=>{fetch('/api/v1/signals').then(r=>r.json()).then((v:Signal[])=>{setSignals(v);v.forEach(s=>fetch(`/api/research/signals/${s.key}/report`).then(r=>r.ok?r.json():null).then((p:Payload|null)=>{if(p)setReports(x=>({...x,[s.key]:p.report.reports[0]}))}))})},[]);const rows=signals.map(s=>({key:s.key,display_name:s.display_name,description:s.description,mean_rank_ic:reports[s.key]?.mean_rank_ic??NaN,rank_ic_ir:reports[s.key]?.rank_ic_ir??NaN,win:reports[s.key]?.rank_ic_positive_rate??NaN,obs:reports[s.key]?.observation_count??0}));const {sorted,by,sort}=useSort(rows,'mean_rank_ic');const th=(title:string,key:keyof typeof rows[number])=><th onClick={()=>by(key)}>{title}{sort.key===key?(sort.desc?' ↓':' ↑'):''}</th>;return <><Header/><main><h1>ETF 因子研究</h1><p>点击因子名称进入详情；点击指标标题排序。</p><div className="table-wrap"><table><thead><tr>{th('因子名称','display_name')}{th('Mean Rank IC','mean_rank_ic')}{th('ICIR','rank_ic_ir')}{th('IC 胜率','win')}{th('观察数','obs')}<th>说明</th></tr></thead><tbody>{sorted.map(s=><tr key={s.key}><td><a className="row-link" href={`/factors/${s.key}`}>{s.display_name}</a><small>{s.key}</small></td><td>{Number.isFinite(s.mean_rank_ic)?s.mean_rank_ic.toFixed(4):'—'}</td><td>{Number.isFinite(s.rank_ic_ir)?s.rank_ic_ir.toFixed(3):'—'}</td><td>{Number.isFinite(s.win)?pct(s.win):'—'}</td><td>{s.obs?s.obs.toLocaleString():'—'}</td><td>{s.description}</td></tr>)}</tbody></table></div></main></>}
function StrategyDirectory(){const [rows,setRows]=useState<StrategySummary[]>([]);useEffect(()=>{fetch('/api/experiments').then(r=>r.json()).then(setRows)},[]);const {sorted,by,sort}=useSort(rows,'created_at');const th=(title:string,key:keyof StrategySummary)=><th onClick={()=>by(key)}>{title}{sort.key===key?(sort.desc?' ↓':' ↑'):''}</th>;return <><Header/><main><h1>策略绩效</h1><p>策略实验目录 · 点击策略名称查看独立绩效详情；点击表头可排序。</p><div className="table-wrap"><table><thead><tr>{th('策略名称','name')}{th('累计收益','total_return')}{th('年化收益','annualized_return')}{th('夏普','sharpe_ratio')}{th('最大回撤','max_drawdown')}{th('卡玛','calmar_ratio')}<th>规则</th></tr></thead><tbody>{sorted.map(s=><tr key={s.experiment_id}><td><a className="row-link" href={`/strategies/${s.experiment_id}`}>{s.name}</a><small>{s.created_at.slice(0,10)}</small></td><td>{pct(s.total_return)}</td><td>{pct(s.annualized_return)}</td><td>{s.sharpe_ratio.toFixed(2)}</td><td>{pct(s.max_drawdown)}</td><td>{s.calmar_ratio.toFixed(2)}</td><td>{s.lookback_days}日动量 · Top{s.top_n} · {s.rebalance_every}日调仓</td></tr>)}</tbody></table></div></main></>}
function StrategyDetail(){const id=decodeURIComponent(location.pathname.split('/').pop()||'');const [exp,setExp]=useState<Experiment|null>(null);const [error,setError]=useState('');useEffect(()=>{fetch(`/api/experiments/${id}`).then(async r=>r.ok?r.json():Promise.reject('策略实验不存在')).then(setExp).catch(setError)},[id]);if(!exp)return <><Header/><main><p>{error||'加载策略详情…'}</p></main></>;const m=exp.backtest.metrics,curve=exp.backtest.equity_curve,dates=curve.map(x=>x.date),base=curve[0]?.equity||1;return <><Header/><main><a className="back" href="/">← 策略目录</a><h1>{exp.name}</h1><p>{exp.config.strategy.lookback_days}日动量 · Top{exp.config.strategy.top_n} · 每{exp.config.strategy.rebalance_every}个交易日调仓</p><section className="metrics">{[['累计收益',pct(m.total_return)],['年化收益',pct(m.annualized_return)],['夏普比率',m.sharpe_ratio.toFixed(2)],['卡玛比率',m.calmar_ratio.toFixed(2)],['最大回撤',pct(m.max_drawdown)]].map(([k,v])=><div className="metric" key={k}><small>{k}</small><strong>{v}</strong></div>)}</section><section className="grid"><Panel title="策略净值"><Chart option={{tooltip:{trigger:'axis'},xAxis:{type:'category',data:dates},yAxis:{type:'value'},dataZoom:[{type:'inside'},{type:'slider'}],series:[{type:'line',showSymbol:false,data:curve.map(x=>x.equity/base),name:'策略净值',color:'#2563eb'}]}}/></Panel><Panel title="策略回撤"><Chart option={{tooltip:{trigger:'axis'},xAxis:{type:'category',data:dates},yAxis:{type:'value'},dataZoom:[{type:'inside'},{type:'slider'}],series:[{type:'line',showSymbol:false,data:curve.map(x=>x.drawdown),areaStyle:{},name:'回撤',color:'#dc2626'}]}}/></Panel></section></main></>}
function App(){const p=location.pathname;return p==='/factors'?<FactorDirectory/>:p.startsWith('/factors/')?<Detail/>:p.startsWith('/strategies/')?<StrategyDetail/>:<StrategyDirectory/>}createRoot(document.getElementById('root')!).render(<App/>);
