import { useEffect, useState } from 'react';
import { api, pct, useSort, Header, ErrorBox, SavedResultTools, type Signal, type Report, type Payload } from '../shared';

export default function FactorDirectory() {
  const [signals, setSignals] = useState<Signal[]>([]); const [reports, setReports] = useState<Record<string, Report>>({}); const [error, setError] = useState('');
  useEffect(() => { api<Signal[]>('/api/v1/signals').then((values) => { setSignals(values); values.forEach((s) => api<Payload>(`/api/research/signals/${encodeURIComponent(s.key)}/report`).then((p) => { const latest = p.report?.reports?.[0]; if (latest) setReports((old) => ({ ...old, [s.key]: latest })); }).catch(() => undefined)); }).catch((e) => setError(e.message)); }, []);
  const rows = signals.map((s) => ({ key: s.key, display_name: s.display_name, description: s.description, mean_rank_ic: reports[s.key]?.mean_rank_ic ?? Number.NaN, rank_ic_ir: reports[s.key]?.rank_ic_ir ?? Number.NaN, win: reports[s.key]?.rank_ic_positive_rate ?? Number.NaN, obs: reports[s.key]?.observation_count ?? 0 })); const { sorted, by, sort } = useSort(rows, 'mean_rank_ic'); const th = (title: string, key: keyof typeof rows[number]) => <th onClick={() => by(key)}>{title}{sort.key === key ? (sort.desc ? ' ↓' : ' ↑') : ''}</th>;
  return <><Header /><main><h1>因子研究</h1><p>点击因子名称进入详情；目录指标来自已保存报告，点击表头排序。</p><SavedResultTools kind="factor" />{error && <ErrorBox>{error}</ErrorBox>}<div className="table-wrap"><table><thead><tr>{th('因子名称', 'display_name')}{th('Mean Rank IC', 'mean_rank_ic')}{th('ICIR', 'rank_ic_ir')}{th('IC 胜率', 'win')}{th('观察数', 'obs')}<th>说明</th></tr></thead><tbody>{sorted.map((s) => <tr key={s.key}><td><a className="row-link" href={`/factors/${encodeURIComponent(s.key)}`}>{s.display_name}</a><small>{s.key}</small></td><td>{Number.isFinite(s.mean_rank_ic) ? s.mean_rank_ic.toFixed(4) : '—'}</td><td>{Number.isFinite(s.rank_ic_ir) ? s.rank_ic_ir.toFixed(3) : '—'}</td><td>{Number.isFinite(s.win) ? pct(s.win) : '—'}</td><td>{s.obs ? s.obs.toLocaleString() : '—'}</td><td>{s.description}</td></tr>)}</tbody></table></div></main></>;
}
